version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306  































      
       
  # rabbitmq:
  #   image: rabbitmq:3.8-rc-management
  #   # restart: always
  #   ports:
  #     - '5673:5672'
  #     - '15673:15672'
  #   volumes:
  #     - .rabbit_mqdata:/usr/share/rabbitmq/data
      
